/**
 * Cookie Service
 * Handles cookie extraction and management for various platforms
 * Extracted from main/index.js for better maintainability
 */

const fs = require('fs')
const path = require('path')
const { existsSync } = require('fs')

class CookieService {
  constructor(config) {
    this.mainWindow = config.mainWindow
    this.cookiesPath = config.cookiesPath
  }

  /**
   * Get cookies from the current webview session
   * @param {string} domain - Domain to get cookies for
   * @returns {Promise<Array>} Array of cookies
   */
  async getCookies(domain = 'youtube.com') {
    if (!this.mainWindow) {
      throw new Error('Main window not initialized')
    }

    try {
      const windowSession = this.mainWindow.webContents.session
      const cookies = await windowSession.cookies.get({ domain })
      return cookies
    } catch (error) {
      console.error('Error getting cookies:', error)
      return []
    }
  }

  /**
   * Save cookies to a file in Netscape format
   * @param {string} filePath - Path to save cookies
   * @param {string} domain - Domain to get cookies for
   * @returns {Promise<boolean>} Success status
   */
  async saveCookiesToFile(filePath, domain = 'youtube.com') {
    try {
      const cookies = await this.getCookies(domain)
      
      if (cookies.length === 0) {
        console.log('No cookies found to save')
        return false
      }

      // Convert to Netscape format
      const netscapeFormat = cookies.map(cookie => {
        const expires = cookie.expirationDate 
          ? Math.floor(cookie.expirationDate) 
          : 0
        return [
          cookie.domain,
          cookie.httpOnly ? 'TRUE' : 'FALSE',
          cookie.path,
          cookie.secure ? 'TRUE' : 'FALSE',
          expires,
          cookie.name,
          cookie.value
        ].join('\t')
      })

      // Add header
      const header = '# Netscape HTTP Cookie File\n# This file was generated by PNUT Downloader\n'
      const content = header + netscapeFormat.join('\n') + '\n'

      // Ensure directory exists
      const dir = path.dirname(filePath)
      if (!existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true })
      }

      fs.writeFileSync(filePath, content)
      console.log(`Saved ${cookies.length} cookies to ${filePath}`)
      return true
    } catch (error) {
      console.error('Error saving cookies:', error)
      return false
    }
  }

  /**
   * Check if cookies file exists and is valid
   * @param {string} filePath - Path to check
   * @returns {boolean}
   */
  hasValidCookies(filePath = null) {
    const cookiesFile = filePath || this.cookiesPath
    if (!cookiesFile || !existsSync(cookiesFile)) {
      return false
    }
    
    try {
      const content = fs.readFileSync(cookiesFile, 'utf-8')
      // Basic check for valid format
      return content.includes('# Netscape') || content.length > 10
    } catch (error) {
      return false
    }
  }

  /**
   * Get the default cookies path
   * @returns {string}
   */
  getCookiesPath() {
    return this.cookiesPath
  }

  /**
   * Extract cookies from specific platforms
   * @param {string} platform - Platform name
   * @returns {Promise<Array>} Cookies
   */
  async getPlatformCookies(platform) {
    const platformDomains = {
      youtube: 'youtube.com',
      youtubeMusic: 'music.youtube.com',
      facebook: 'facebook.com',
      instagram: 'instagram.com',
      twitter: 'twitter.com',
      tiktok: 'tiktok.com',
      dailymotion: 'dailymotion.com'
    }

    const domain = platformDomains[platform] || 'youtube.com'
    return this.getCookies(domain)
  }
}

module.exports = CookieService
