export const IPC_CHANNELS = {
  ACCESS_FILE: 'accessFile',
  CHECK_DEPENDENCIES: 'check-dependencies',
  GET_DEPENDENCY_STATUS: 'get-dependency-status',
  CHECK_FILE_EXISTS: 'checkFileExists',
  CHECK_YTDLP_UPDATE: 'check-ytdlp-update',
  CREATE_DIRECTORY: 'create-directory',
  DELETE_FILE: 'deleteFile',
  DELETE_MULTIPLE_FILES: 'deleteMultipleFiles',
  DOWNLOAD_UPDATE: 'download-update',
  DOWNLOAD_VIDEO: 'downloadVideo',
  FETCH_PLAYLIST_ENTRIES: 'fetch-playlist-entries',
  FETCH_VIDEO_INFO: 'fetch-video-info',
  FILE_EXISTS: 'fileExists',
  GET_APP_VERSION: 'get-app-version',
  GET_FFMPEG_VERSION: 'getFfmpegVersion',
  GET_PATH: 'get-path',
  GET_YOUTUBE_COOKIES: 'getYoutubeCookies',
  GET_YOUTUBE_INFO: 'get-youtube-info',
  GET_YT_VERSION: 'getYtVersion',
  SAVE_WEBVIEW_COOKIES: 'save-webview-cookies',
  SAVE_DOWNLOAD_STATE: 'save-download-state',
  HANDLE_FILE_DELETION: 'handleFileDeletion',
  INSTALL_UPDATE: 'install-update',
  LOAD_DOWNLOAD_STATE: 'load-download-state',
  OPEN_EXTERNAL: 'openExternal',
  OPEN_FILE: 'openFile',
  OPEN_PATH: 'openPath',
  OPEN_WEBVIEW: 'open-webview',
  PAUSE_DOWNLOAD: 'pauseDownload',
  PROXY_IMAGE: 'proxy-image',
  READ_DIRECTORY: 'read-directory',
  RESUME_DOWNLOAD: 'resumeDownload',
  SELECT_FOLDER: 'select-folder',
  SHOW_CONFIRM_DIALOG: 'show-confirm-dialog',
  SHOW_MESSAGE_BOX: 'show-message-box',
  SHOW_VIDEO_URL_NOTIFICATION: 'show-video-url-notification',
  UPDATE_FFMPEG: 'update-ffmpeg',
  UPDATE_YTDLP: 'update-ytdlp'
}

export const IPC_EVENTS = {
  CHECK_FOR_UPDATES: 'check-for-updates',
  DEPENDENCY_PROGRESS: 'dependency-progress',
  DOWNLOAD_PROGRESS: 'download-progress',
  FILE_DELETED: 'file-deleted',
  FILE_DELETED_SUCCESS: 'file-deleted-successfully',
  FILE_DELETION_FAILED: 'file-deletion-failed',
  UPDATE_AVAILABLE: 'update-available',
  UPDATE_DOWNLOADED: 'update-downloaded',
  UPDATE_DOWNLOAD_PROGRESS: 'update-download-progress',
  UPDATE_ERROR: 'update-error',
  VIDEO_URL_DETECTED: 'video-url-detected',
  WEBVIEW_URL_UPDATE: 'webview-url-update',
  YTDLP_UPDATED: 'ytdlp-updated'
}
