const TITLE_TIMESTAMP_PATTERN = /_\d{8}_\d{6}_\d{3}/g

/**
 * Build a UTC timestamp that sorts chronologically as plain text.
 * @param {number|string|Date} value
 * @returns {string}
 */
export const formatTitleTimestamp = (value = Date.now()) => {
  const date = value instanceof Date ? value : new Date(value)
  const safeDate = Number.isNaN(date.getTime()) ? new Date() : date
  return safeDate
    .toISOString()
    .replace(/[-:]/g, '')
    .replace('T', '_')
    .replace('.', '_')
    .replace('Z', '')
}

/**
 * Remove timestamps previously generated by appendTitleTimestamp.
 * @param {string} title
 * @returns {string}
 */
export const stripTitleTimestamp = (title) =>
  String(title || '')
    .replace(TITLE_TIMESTAMP_PATTERN, '')
    .replace(/_{2,}/g, '_')
    .replace(/^_|_$/g, '')
    .trim()

/**
 * Append one stable timestamp, keeping the complete title under 200 characters.
 * @param {string} title
 * @param {number|string|Date} value
 * @returns {string}
 */
export const appendTitleTimestamp = (title, value = Date.now()) => {
  const timestamp = formatTitleTimestamp(value)
  const suffix = `_${timestamp}`
  const baseTitle = stripTitleTimestamp(title) || 'Unknown Video'
  const maxBaseLength = Math.max(1, 200 - suffix.length)
  return `${baseTitle.substring(0, maxBaseLength).trim()}${suffix}`
}
