import { app, shell, BrowserWindow, ipcMain, session, dialog } from 'electron'
import { join } from 'path'
import { electronApp, optimizer, is } from '@electron-toolkit/utils'
import icon from '../../resources/icon.png?asset'
import { existsSync, mkdirSync, writeFileSync } from 'fs'
import { spawn } from 'child_process'

const ffmpegPath = app.isPackaged
  ? join(process.resourcesPath, 'ffmpeg.exe')
  : join(__dirname, '../../public/ffmpeg.exe')
const ffprobePath = app.isPackaged
  ? join(process.resourcesPath, 'ffprobe.exe')
  : join(__dirname, '../../public/ffprobe.exe')
let mainWindow
const cookiesPath = app.isPackaged
  ? join(process.resourcesPath, 'cookies.txt')
  : join(__dirname, '../../public/cookies.txt')

const ytdlpPath = app.isPackaged
  ? join(process.resourcesPath, 'yt-dlp.exe')
  : join(__dirname, '../../public/yt-dlp.exe')
// Set icon path based on OS
let iconPath = ''
switch (process.platform) {
  case 'win32':
    iconPath = join(__dirname, '../../public/icon.ico')
    break
  case 'linux':
    iconPath = icon
    break
  default:
    iconPath = join(process.resourcesPath, 'icon.png')
}

// Prevent multiple instances
const gotTheLock = app.requestSingleInstanceLock()
if (!gotTheLock) {
  app.quit()
} else {
  app.on('second-instance', () => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore()
      mainWindow.focus()
    }
  })
}

function createWindow() {
  if (mainWindow) return // Prevent duplicate windows

  mainWindow = new BrowserWindow({
    width: 1200,
    height: 670,
    minWidth: 1200,
    minHeight: 670,
    maxWidth: 1200,
    maxHeight: 670,
    autoHideMenuBar: true,
    icon: iconPath,

    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      sandbox: false,
      webviewTag: true, // Disabled by default (safer)
      nodeIntegration: false,
      contextIsolation: true
    }
  })

  mainWindow.once('ready-to-show', () => {
    mainWindow.show()
  })

  mainWindow.on('closed', () => {
    mainWindow = null // Cleanup memory
  })

  mainWindow.webContents.setWindowOpenHandler((details) => {
    shell.openExternal(details.url)
    return { action: 'deny' }
  })

  if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
    mainWindow.loadURL(process.env['ELECTRON_RENDERER_URL'])
  } else {
    mainWindow.loadFile(join(__dirname, '../renderer/index.html'))
  }
}

app.whenReady().then(() => {
  electronApp.setAppUserModelId('com.electron')

  app.on('browser-window-created', (_, window) => {
    optimizer.watchWindowShortcuts(window)
  })

  ipcMain.on('open-webview', (event, url) => {
    console.log('Received YouTube Video URL:', url)
    if (mainWindow) {
      mainWindow.webContents.send('webview-url-update', url)
    }
  })

  createWindow()

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})
async function updateCookiesFile() {
  try {
    const cookies = await session.defaultSession.cookies.get({ domain: '.youtube.com' })
    if (!cookies.length) {
      console.error('No YouTube cookies found.')
      return
    }

    const lines = [
      '# Netscape HTTP Cookie File',
      '# This file is generated by Electron for use by yt-dlp.',
      '# This file was last updated on ' + new Date().toString(),
      ''
    ]

    cookies.forEach((cookie) => {
      let domain = cookie.domain
      if (!domain.startsWith('.')) {
        domain = '.' + domain
      }
      const includeSubdomains = 'TRUE'
      const isSecure = cookie.secure ? 'TRUE' : 'FALSE'
      const expiry = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0

      const line = [
        domain,
        includeSubdomains,
        cookie.path,
        isSecure,
        expiry,
        cookie.name,
        cookie.value
      ].join('\t')

      lines.push(line)
    })

    const fileContent = lines.join('\n')
    writeFileSync(cookiesPath, fileContent, 'utf8')
    console.log('Cookies updated successfully at:', cookiesPath)
  } catch (error) {
    console.error('Error updating cookies:', error)
  }
}
ipcMain.handle('getYoutubeCookies', async () => {
  await updateCookiesFile()
  return cookiesPath
})
// function formatDuration(seconds) {
//   const minutes = Math.floor(seconds / 60);
//   const remainingSeconds = seconds % 60;
//   return `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
// }
ipcMain.handle('fetch-video-info', async (event, url) => {
  return new Promise((resolve, reject) => {
    const args = ['-J', url];
    const proc = spawn(ytdlpPath, args);

    let stdout = '';
    let stderr = '';

    proc.stdout.on('data', (data) => {
      stdout += data.toString();
    });

    proc.stderr.on('data', (data) => {
      stderr += data.toString();
    });

    proc.on('close', (code) => {
      if (code !== 0) {
        reject(new Error(`yt-dlp exited with code ${code}. Error:\n${stderr}`));
        return;
      }

      try {
        const json = JSON.parse(stdout);

        const title = json.title || '';
        let thumbnail = '';
        if (Array.isArray(json.thumbnails) && json.thumbnails.length > 0) {
          thumbnail = json.thumbnails[json.thumbnails.length - 1].url;
        }

        const timeDuration = json.duration || 0; 
        
        // Duration in seconds
        const duration = formatDuration(timeDuration); // Format duration

        const filename = title && json.ext ? `${title}.${json.ext}` : title;

        resolve({ title, thumbnail, filename, duration, duration });
      } catch (err) {
        reject(new Error(`Failed to parse JSON from yt-dlp: ${err.message}`));
      }
    });
  });
});

// Helper function to format duration
function formatDuration(seconds) {
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  return `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
}

// 🛠 Ensure ffmpeg & ffprobe exist
if (!existsSync(ffmpegPath) || !existsSync(ffprobePath)) {
  console.error('FFmpeg or FFprobe not found! Please install FFmpeg.')
}
let downloadProcess = null;

const startDownload = async (event, options) => {
  try {
    if (downloadProcess) {
      event.sender.send("download-progress", { status: "A download is already in progress!" });
      return;
    }

    const { url, isAudioOnly, selectedFormat, selectedQuality, saveTo } = options;

    if (!url || typeof url !== "string") throw new Error("Invalid URL.");
console.log("options",options);

    const finalQualityVideo = selectedQuality.replace(/[pP]$/, "");

    const formatSpecifier = isAudioOnly
      ? `--extract-audio --audio-format mp3 --audio-quality best`
      : `-f bestvideo[height<=${finalQualityVideo}]+bestaudio/best`;

    let downloadDir;
    if (saveTo === "Desktop") {
      downloadDir = join(app.getPath("desktop"), "pnutdownloader");
    } else {
      downloadDir = join(app.getPath("downloads"), "pnutdownloader");
    }

    if (!existsSync(downloadDir)) {
      mkdirSync(downloadDir, { recursive: true });
    }

    const downloadPath = join(downloadDir, "%(title)s.%(ext)s");

    const args = [
      "--continue",
      ...formatSpecifier.split(" "),
      "--ffmpeg-location", ffmpegPath,
      "-o", downloadPath,
      "--cookies", cookiesPath,
      url, "--newline", "--ignore-errors", "--progress"
    ];

    downloadProcess = spawn(ytdlpPath, args, { windowsHide: true });

    downloadProcess.stdout.on("data", (data) => {
      const line = data.toString().trim();
      event.sender.send("download-progress", { message: line });
    });

    downloadProcess.stderr.on("data", (data) => {
      const errorMessage = data.toString().trim();
      console.error("yt-dlp Error:", errorMessage);
      event.sender.send("download-progress", { error: errorMessage });
    });

    downloadProcess.on("close", (code) => {
      downloadProcess = null;
      event.sender.send("download-progress", { status: "Download complete!", file: downloadPath });
    });

  } catch (err) {
    console.error("Download error:", err);
    event.sender.send("download-progress", { error: err.message });
    throw err;
  }
};
ipcMain.handle('show-message-box', async (_, options) => {
  return dialog.showMessageBox(mainWindow, options);
});
ipcMain.handle("downloadVideo", async (event, options) => {
  console.log("Starting download...");
  await startDownload(event, options);
});

ipcMain.handle('resumeDownload', async (event, options) => {
  if (!downloadProcess) {
    console.log("Resuming download...");
    await startDownload(event, options);
    return true;
  }
  return false;
});
const treeKill = require('tree-kill');
ipcMain.handle('pauseDownload', () => {
  console.log("Attempting to pause download...");
  if (downloadProcess) {
    console.log("Killing download process with PID:", downloadProcess.pid);
    treeKill(downloadProcess.pid, 'SIGKILL', (err) => {
      if (err) {
        console.error("Failed to kill process tree:", err);
      } else {
        console.log("Process tree killed successfully.");
      }
    });
    downloadProcess = null;
    return true;
  }
  console.log("No active download to pause.");
  return false;
});
function saveDownloadState(state) {
  const filePath = join(app.getPath('userData'), 'downloadState.json')
  fs.writeFileSync(filePath, JSON.stringify(state))
}

ipcMain.handle('load-download-state', () => {
  const filePath = join(app.getPath('userData'), 'downloadState.json')
  return fs.existsSync(filePath) ? JSON.parse(fs.readFileSync(filePath, 'utf-8')) : null
})
